### ISSUE TITLE
Call to undefined method Extension_EmailTemplateFilter::getDataParam() in extension.driver.php:365

### ISSUE THREAD

**Issue by siimsoni** [symphonists/emailtemplatefilter#5]
I am getting this undefined method error. This method is obviously undefined in the class, and it has never been part of the Symphony's Extension parent class. I went back in history for all the releases of Symphony and all the releases of this extension, and it is not defined anywhere.

**Comment by nitriques** [comment]
It's been fixed in 1.3.0
